spring:
  cloud:
    gateway:
      routes:
#        - id: baidu_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=whw,baidu
#
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=whw,qq

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**,/hello #/hello用于压力测试的简单服务测试
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment} # 将/api/(?<segment>.*) 截取为 /$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        - id: member_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        # nginx反向代理过来的请求进行路由处理（必须放置在最后）
        - id: gulimall_host_router
          uri: lb://gulimall-product
          predicates:
            #- Path=/api/**
            - Host=**.gulimall.com


            # 前端项目的请求路径都带/api