spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 日期以json返回时，按此格式化
  thymeleaf:
    cache: false # 开发时暂时关闭，能够看到实时效果
  redis:
    host: 192.168.56.10
    port: 6379 # 默认6379 可以不写


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #设置主键自增
      logic-delete-value: 1 # mybatis-plus默认1为逻辑已删除
      logic-not-delete-value: 0 # mybatis-plus默认0为逻辑未删除
server:
  port: 10000
logging:
  level:
    com.atguigu.gulimall: debug # 控制台打印sql日志

