spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    在nacos配置中心配置了，开发中临时使用
    alicloud:
      access-key: LTAI5t65mPsBz6PhbREpcsAk
      secret-key: hWKPQUYZKm0uwy03Cw2Aizk3aVHlol
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: gulimall-brands-logo
  application:
    name: gulimall-third-party

server:
  port: 30000