spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    在nacos配置中心配置了，开发中临时使用
    alicloud:
      access-key: LTAI5t65mPsBz6PhbREpcsAk
      secret-key: hWKPQUYZKm0uwy03Cw2Aizk3aVHlol
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: gulimall-brands-logo

      sms:
        accessKeyId: LTAI5t7vJ5HhNKR2y5RVcirt
        accessKeySecret: yXeqlGqN6P8LsV9wbCHj2ckf2GUJQr
        endpoint: dysmsapi.aliyuncs.com
        signName: 阿里云短信测试
        templateCode: SMS_154950909


  application:
    name: gulimall-third-party

server:
  port: 40000